/*
 * This source file was generated by the Gradle 'init' task
 */
package projects;

import javax.swing.SwingUtilities;

public class App {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new MatchGUI().setVisible(true);
        });
    }
}
